// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hndpbqddkjohrwbmqgnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhuZHBicWRka2pvaHJ3Ym1xZ25tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMjYyMjgsImV4cCI6MjA3MTYwMjIyOH0.PRz8PqbKb3cBZEYkBbio_8dT1dM8QFm823ET1o8Jy8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});